# .github/dependabot.yml
version: 2
updates:
  # Maintain dependencies for Python (pip) defined in pyproject.toml
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    commit-message:
      prefix: "chore(deps)"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    commit-message:
      prefix: "chore(ci)"
