services:
  # The on-demand Minecraft proxy service
  nether-bridge:
    container_name: nether-bridge
    image: ghcr.io/meek2100/mcbd-proxy:latest # Updated image name
    restart: unless-stopped
    networks:
      - mc-network
    ports:
      - "19133:19133/udp" # Port for Bedrock server (NB_1_LISTEN_PORT)
      - "25565:25565/udp" # Port for Java server discovery (NB_2_LISTEN_PORT)
      - "25565:25565/tcp" # Port for Java server gameplay (needs to be exposed by Docker)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Required for Docker management
      # Optionally mount JSON config files (uncomment to use these instead of environment variables)
      # - ./data/nether-bridge/settings.json:/app/settings.json
      # - ./data/nether-bridge/servers.json:/app/servers.json
    environment:
      # General settings
      - LOG_LEVEL=INFO
      - NB_IDLE_TIMEOUT=300
      - NB_PLAYER_CHECK_INTERVAL=60
      - NB_QUERY_TIMEOUT=5
      - NB_SERVER_READY_MAX_WAIT=120
      - NB_INITIAL_BOOT_READY_MAX_WAIT=180
      - NB_SERVER_STARTUP_DELAY=5
      - NB_INITIAL_SERVER_QUERY_DELAY=10

      # --- Server Definitions ---
      # Server 1: Bedrock Survival
      - NB_1_NAME=Bedrock Survival
      - NB_1_SERVER_TYPE=bedrock
      - NB_1_LISTEN_PORT=19133
      - NB_1_CONTAINER_NAME=mc-bedrock # Matches service name below
      - NB_1_INTERNAL_PORT=19132

      # Server 2: Java Creative
      - NB_2_NAME=Java Creative
      - NB_2_SERVER_TYPE=java
      - NB_2_LISTEN_PORT=25565
      - NB_2_CONTAINER_NAME=mc-java # Matches service name below
      - NB_2_INTERNAL_PORT=25565

  # A managed Minecraft Bedrock server
  mc-bedrock:
    container_name: mc-bedrock
    image: itzg/minecraft-bedrock-server:latest
    restart: "no" # IMPORTANT: Must be 'no' for proxy management
    networks:
      - mc-network
    environment:
      - EULA=TRUE
    volumes:
      - ./data/mc-bedrock:/data

  # A managed Minecraft Java server
  mc-java:
    container_name: mc-java
    image: itzg/minecraft-server:latest
    restart: "no"
    networks:
      - mc-network
    environment:
      - EULA=TRUE
      - TYPE=PAPER # Example: Using a specific server type
    volumes:
      - ./data/mc-java:/data

networks:
  mc-network:
    driver: bridge

# --- Optional Services ---
# If you wish to provide an in-game server list to Minecraft Bedrock players,
# you can use the bedrock-connect service. This is separate from Nether-bridge's
# core proxy and orchestration functionality. Uncomment and add to your compose stack
# if needed.
#
# bedrock-connect:
#   container_name: bedrock-connect
#   image: pugmatt/bedrockconnect:latest
#   restart: unless-stopped
#   ports:
#     - "19132:19132/udp" # Default MCBE port players connect to first
#   volumes:
#     # This file should list the proxy's ports (e.g., 19133)
#     - ./data/connect/serverlist.json:/config/serverlist.json