services:
  # The on-demand Minecraft proxy service
  nether-bridge:
    container_name: nether-bridge
    image: ghcr.io/meek2100/mcbd-proxy:develop
    restart: unless-stopped
    networks:
      - mc-network
    ports:
      - "19133:19133/udp" # Default MCBE port players connect to first
      - "25566:25566/udp" # Port for Java server discovery (NB_2_LISTEN_PORT)
      - "25566:25566/tcp" # Port for Java server gameplay (needs to be exposed by Docker)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Required for Docker management
      - /home/meek2100/docker/nether-bridge/settings.json:/app/settings.json
      - /home/meek2100/docker/nether-bridge/servers.json:/app/servers.json
    #  - .:/app # Local mount for live code changes
    environment:
      # General settings
      # - LOG_LEVEL=INFO
      # - NB_IDLE_TIMEOUT=300
      # - NB_PLAYER_CHECK_INTERVAL=60
      - NB_QUERY_TIMEOUT=5
      - NB_SERVER_READY_MAX_WAIT=120
      - NB_INITIAL_BOOT_READY_MAX_WAIT=180
      - NB_SERVER_STARTUP_DELAY=5
      - NB_INITIAL_SERVER_QUERY_DELAY=10

      # --- Server Definitions ---
      # Server 1: Bedrock Survival (COMMENTED OUT FOR TESTING)
      # - NB_1_NAME=Bedrock Survival
      # - NB_1_SERVER_TYPE=bedrock
      # - NB_1_LISTEN_PORT=19133
      # - NB_1_CONTAINER_NAME=mc-bedrock
      # - NB_1_INTERNAL_PORT=19132

      # Server 2: Java Creative
      - NB_2_NAME=Java Creative
      - NB_2_SERVER_TYPE=java
      - NB_2_LISTEN_PORT=25565
      - NB_2_CONTAINER_NAME=mc-java
      - NB_2_INTERNAL_PORT=25565
    # TEMPORARY: Install net-tools for debugging
    command: /bin/bash -c "apt-get update && apt-get install -y net-tools && python nether_bridge.py" # <--- ADD THIS LINE
    
  # A managed Minecraft Bedrock server (COMMENTED OUT FOR TESTING)
  # mc-bedrock:
  #   container_name: mc-bedrock
  #   image: itzg/minecraft-bedrock-server:latest
  #   restart: "no"
  #   networks:
  #     - mc-network
  #   environment:
  #     - EULA=TRUE
  #   volumes:
  #     - /home/meek2100/docker/data/mc-bedrock:/data

  # A managed Minecraft Java server
  mc-java:
    container_name: mc-java
    image: itzg/minecraft-server:latest
    restart: "no"
    networks:
      - mc-network
    environment:
      - EULA=TRUE
      - TYPE=PAPER
      - JVM_ARGS=-Xmx1G -Xms1G
    volumes:
      - /home/meek2100/docker/mc-java:/data

networks:
  mc-network:
    driver: bridge