services:
  nether-bridge:
    container_name: nether-bridge
    build: . # Build the image from the Dockerfile
    restart: unless-stopped
    networks:
      - mc-network
    ports:
      - "19132:19132/udp"
      - "25565:25565/tcp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount the configuration files for the test environment
      - ./settings.json:/app/settings.json
      - ./servers.json:/app/servers.json
    # REMOVED all environment variables to rely solely on the JSON files

  mc-bedrock:
    container_name: mc-bedrock
    image: itzg/minecraft-bedrock-server:latest
    restart: "no"
    networks:
      - mc-network
    environment:
      - EULA=TRUE

  mc-java:
    container_name: mc-java
    image: itzg/minecraft-server:latest
    restart: "no"
    networks:
      - mc-network
    environment:
      - EULA=TRUE
      - TYPE=PAPER

networks:
  mc-network:
    driver: bridge