# pyproject.toml
[project]
name = "nether-bridge"
version = "1.0.0"
description = "An intelligent, on-demand proxy for Minecraft servers running in Docker."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT License" }
authors = [
    { name = "meek2100" },
]
keywords = ["minecraft", "proxy", "docker", "on-demand"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "docker",
    "mcstatus",
    "prometheus-client",
    "structlog",
    "colorama",
]

[project.urls]
Homepage = "https://github.com/meek2100/nether-bridge"
"Bug Tracker" = "https://github.com/meek2100/nether-bridge/issues"

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-mock",
    "pytest-cov",
    "ruff",
    "python-dotenv",
    "requests",
]

[tool.ruff]
line-length = 88
exclude = [
    ".git",
    ".venv",
    ".pytest_cache",
    "build",
    "dist",
    "examples",
]

[tool.ruff.lint]
select = ["E", "W", "F", "I"]
ignore = []

[tool.ruff.lint.per-file-ignores]
# "tests/*.py" = ["S101"] # Example: Ignore assert statements in tests if needed.

[tool.pytest.ini_options]
markers = [
    "unit: marks tests as unit tests that do not require external services.",
    "integration: marks tests as integration tests that require Docker Compose.",
]