# This file centralizes project metadata and tool configuration.

[project]
name = "nether-bridge"
version = "1.0.0"
description = "An intelligent, on-demand proxy for Minecraft servers running in Docker."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT License" }
authors = [
    { name = "meek2100" },
]
keywords = ["minecraft", "proxy", "docker", "on-demand"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/meek2100/nether-bridge"
"Bug Tracker" = "https://github.com/meek2100/nether-bridge/issues"


# --- Tool Configurations ---

[tool.ruff]
line-length = 88
# Exclude the same common directories as Black.
exclude = [
    ".git",
    ".venv",
    ".pytest_cache",
    "build",
    "dist",
    "examples",
]
# Enable the 'E' and 'W' series (pycodestyle) and 'F' series (pyflakes) rules by default.
select = ["E", "W", "F", "I"] # "I" for isort-like checks
ignore = [] # Ruff handles Black compatibility, so no need to ignore E203, W503 directly.

[tool.ruff.per-file-ignores]
# If you have specific files or patterns where you want to ignore certain rules, add them here.
# For example: "tests/*.py" = ["S101"] # Ignore assert statements in tests.