# This file centralizes project metadata and tool configuration.

[project]
name = "nether-bridge"
version = "1.0.0"
description = "An intelligent, on-demand proxy for Minecraft servers running in Docker."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT License" }
authors = [
    { name = "meek2100" },
]
keywords = ["minecraft", "proxy", "docker", "on-demand"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/meek2100/nether-bridge"
"Bug Tracker" = "https://github.com/meek2100/nether-bridge/issues"


# --- Tool Configurations ---

[tool.black]
# Set the maximum line length to the PEP 8 standard.
line-length = 79
# Exclude common directories from formatting.
exclude = '''
/(
    \.git
  | \.venv
  | \.pytest_cache
  | build
  | dist
  | examples
)/
'''

[tool.flake8]
# Set the max line length to match black's configuration.
max-line-length = 79
# Ignore specific flake8 errors that conflict with black's automatic formatting.
extend-ignore = "E203, W503"
# Exclude the same common directories.
exclude = [
    ".git",
    ".venv",
    ".pytest_cache",
    "build",
    "dist",
    "examples",
]