# Start from the official Minecraft server image
FROM itzg/minecraft-server:latest

# Declare the version as a build argument with a default value
ARG JAVA_TYPE=PAPER
ARG JAVA_VERSION=1.20.1

# Set environment variables for the installer script
ENV EULA="TRUE"
ENV TYPE=${JAVA_TYPE}
ENV VERSION=${JAVA_VERSION}

# Run the installer script
RUN /start --install-only

# Unset the installer variables
ENV TYPE=""
ENV VERSION=""