# Use the buildkit syntax to pass build arguments
#syntax=docker/dockerfile:1

# Start from the official Bedrock server image
FROM itzg/minecraft-bedrock-server:latest

# The server files will be installed in the /data directory
WORKDIR /data

# Use the --dns flag within the RUN command to ensure reliable name resolution.
RUN --mount=type=cache,target=/var/cache/apt \
    --network=default \
    --dns=8.8.8.8 \
    sh -c 'apt-get update && apt-get install -y curl unzip && \
    curl -L -o bedrock.zip \
    -A "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" \
    "https://www.minecraft.net/bedrockdedicatedserver/bin-linux/bedrock-server-1.20.81.01.zip" && \
    unzip bedrock.zip && \
    rm bedrock.zip && \
    apt-get purge -y --auto-remove curl unzip && \
    rm -rf /var/lib/apt/lists/*'