name: Build and Push MCBD Proxy Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile # <--- UPDATED THIS LINE
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mcbd-proxy:latest
            ghcr.io/${{ github.repository_owner }}/mcbd-proxy:${{ github.sha }}
