# .github/workflows/develop-build.yml
name: Build and Push Development Image

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  call-reusable-build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      tags_list: ghcr.io/${{ github.repository_owner }}/mcbd-proxy:develop
    secrets: inherit