name: Build and Push Development Image

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  call-reusable-build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      image_name: ghcr.io/${{ github.repository_owner }}/mcbd-proxy # Development Name
      tags: type=raw,value=develop,enable=true
      app_version: develop
    secrets: inherit