# .github/workflows/fast-validation.yml
name: Fast Validation (Lint & Unit Tests)

on: [push]

permissions:
  contents: read

jobs:
  lint-and-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Dependencies with Poetry
        run: poetry install --no-root

      - name: Lint with ruff
        run: poetry run ruff check .

      - name: Check formatting with ruff
        run: poetry run ruff format --check .

      - name: Run Unit Tests
        run: >
          poetry run pytest -m unit
          --cov=main
          --cov=proxy
          --cov=config
          --cov=docker_manager
          --cov=metrics
          --cov-report=term-missing