# .github/workflows/fast-validation.yml
name: Fast Validation (Lint & Unit Tests)

# This workflow runs on every push to any branch.
on: [push]

permissions:
  contents: read

jobs:
  lint-and-unit-test:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # Cache dependencies for faster runs

      - name: Install Dependencies
        run: pip install -r tests/requirements-dev.txt

      - name: Lint with ruff
        run: ruff check .

      - name: Check formatting with ruff
        run: ruff format --check .

      - name: Run Unit Tests
        # This command now uses markers to run only the fast unit tests.
        # It also measures coverage against all the new application modules.
        run: >
          pytest -m unit
          --cov=main
          --cov=proxy
          --cov=config
          --cov=docker_manager
          --cov=metrics
          --cov-report=term-missing