# .github/workflows/fast-validation.yml
name: Fast Validation (Lint & Unit Tests)

on: [push]

permissions:
  contents: read

jobs:
  lint-and-unit-test:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: Install Poetry (if not in path)
        run: |
          if ! command -v poetry &> /dev/null; then
              curl -sSL https://install.python-poetry.org | python3 -
              echo "$POETRY_HOME/bin" >> $GITHUB_PATH
              echo "POETRY_HOME=$POETRY_HOME" >> $GITHUB_ENV
              echo "POETRY_VIRTUALENVS_IN_PROJECT=true" >> $GITHUB_ENV
          fi

      - name: Install Dependencies with Poetry
        run: poetry install --no-root --sync

      - name: Lint with ruff
        run: poetry run ruff check .

      - name: Check formatting with ruff
        run: poetry run ruff format --check .

      - name: Run Unit Tests
        run: >
          poetry run pytest -m unit
          --cov=main
          --cov=proxy
          --cov=config
          --cov=docker_manager
          --cov=metrics
          --cov-report=term-missing