# .github/workflows/fast-validation.yml
name: Fast Validation (Lint & Unit Tests)

on: [push]

permissions:
  contents: read

jobs:
  lint-and-unit-test:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install ".[dev]"

      - name: Lint with ruff
        run: ruff check .

      - name: Check formatting with ruff
        run: ruff format --check .

      - name: Run Unit Tests
        run: >
          pytest -m unit
          --cov=main
          --cov=proxy
          --cov=config
          --cov=docker_manager
          --cov=metrics
          --cov-report=term-missing