name: Manual Load Test - Java

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      clients:
        description: 'Number of concurrent clients'
        required: true
        default: '25'
  
  # Also runs automatically on pushes to the feature branch
  push:
    branches:
      - 'feature/load-testing'

jobs:
  load-test-java:
    name: Run Java Load Test
    runs-on: [self-hosted, ubuntu-latest]
    env:
      JAVA_VERSION: "1.20.1"
      JAVA_TYPE: "PAPER"
      BEDROCK_VERSION: "1.20.81.01"
      BEDROCK_DOWNLOAD_URL: https://www.minecraft.net/bedrockdedicatedserver/bin-linux/bedrock-server-1.20.81.01.zip
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up and run test environment
        run: |
          echo "--- Building and starting services ---"
          docker compose -f tests/docker-compose.tests.yml up --build -d
          
          echo "--- Waiting for nether-bridge to be healthy ---"
          timeout=120
          start_time=$(date +%s)
          while true; do
            status=$(docker inspect --format '{{.State.Health.Status}}' nether-bridge || echo "error")
            if [ "$status" = "healthy" ]; then
              echo "Nether-bridge is healthy."
              break
            fi
            if [ "$(($(date +%s) - start_time))" -ge "$timeout" ]; then
              echo "Timeout waiting for nether-bridge container to become healthy."
              docker compose -f tests/docker-compose.tests.yml logs --no-color
              exit 1
            fi
            sleep 5
          done

      - name: Run Java Load Test Script
        run: |
          echo "--- Running load test against Java server ---"
          docker compose -f tests/docker-compose.tests.yml exec -T nb-tester \
            python tests/load_tester.py \
              --server-type java \
              --clients ${{ github.event.inputs.clients || '25' }}

      - name: Dump container logs on failure
        if: failure()
        run: |
          echo "--- A step failed. Dumping all container logs. ---"
          docker compose -f tests/docker-compose.tests.yml logs --no-color