name: Build and Push Release Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  call-reusable-build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      image_name: ghcr.io/${{ github.repository_owner }}/nether-bridge # Final Production Name
      tags: |
        type=semver,pattern={{version}}
        type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
      app_version: ${{ github.ref_type == 'tag' && github.ref_name || 'latest' }}
    secrets: inherit