# .github/workflows/main-build.yml
name: Build and Push Release Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  get-tags:
    runs-on: ubuntu-latest
    outputs:
      tags_list: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/mcbd-proxy
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

  call-reusable-build:
    needs: get-tags
    uses: ./.github/workflows/reusable-build.yml
    with:
      tags_list: ${{ needs.get-tags.outputs.tags_list }}
    secrets: inherit