name: Pull Request Validation

# This workflow runs on any pull request that targets the 'main' branch.
on:
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest # Use a standard GitHub-hosted runner with Docker pre-installed.
    
    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install all necessary Python dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-mock # Install testing-specific dependencies

      # Step 4: Run the fast Unit Tests first
      - name: Run Unit Tests
        run: pytest tests/test_nether_bridge.py

      # Step 5: Run the full Integration Tests
      # We set VM_HOST_IP to 127.0.0.1 because in the GitHub Actions runner,
      # the Docker containers and the test script are on the same "machine".
      - name: Run Integration Tests
        env:
          VM_HOST_IP: 127.0.0.1
        # Point conftest.py to the correct compose file
        run: pytest -s --log-cli-level=INFO tests/integration_tests/