name: Pull Request Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  validate-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure local_env.py is absent in CI
        run: |
          rm -f tests/local_env.py || true

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set COMPOSE_PROJECT_PATH for CI environment
        run: echo "COMPOSE_PROJECT_PATH=$(pwd)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Force Rebuild Test Images (no cache)
        run: |
          docker compose -f tests/docker-compose.tests.yml build --no-cache nether-bridge nb-tester

      - name: Start Test Environment
        run: |
          docker compose -f tests/docker-compose.tests.yml up -d --remove-orphans
        id: start-env

      - name: Show Directory Structure Inside Tester Container
        run: |
          echo "Listing files and directory structure inside the 'nb-tester' container at /app..."
          docker compose -f tests/docker-compose.tests.yml exec -T nb-tester ls -lR /app

      - name: Run all tests
        run: |
          PROXY_IP=$(docker inspect nether-bridge | jq -r '.[0].NetworkSettings.Networks | .[] | .IPAddress')
          echo "Found nether-bridge IP: ${PROXY_IP}"
          docker compose -f tests/docker-compose.tests.yml exec -T nb-tester env CI_MODE=true PROXY_IP=${PROXY_IP} python -m pytest --cov=nether_bridge --cov-report term-missing --compose-file /app/tests/docker-compose.tests.yml
        id: run-tests

      - name: Dump All Container Logs on Failure
        if: ${{ failure() }}
        run: |
          echo "--- DUMPING ALL CONTAINER LOGS DUE TO FAILURE ---"
          docker compose -f tests/docker-compose.tests.yml ps -a
          echo "--- Docker Compose logs (all services) ---"
          docker compose -f tests/docker-compose.tests.yml logs --no-color
          echo "--- END LOG DUMP ---"

      - name: Tear down test environment
        if: always()
        run: |
          echo "Tearing down Docker Compose environment..."
          docker compose -f tests/docker-compose.tests.yml down -v --remove-orphans