name: Pull Request Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  validate-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v1

      - name: Start Test Environment
        run: |
          # Use docker compose to create the containers but not start them
          docker compose -f tests/docker-compose.tests.yml create --build
          # Start only the proxy service
          docker compose -f tests/docker-compose.tests.yml start nether-bridge

      - name: Wait for Proxy to be Healthy
        run: |
          echo "Waiting for nether-bridge to be healthy..."
          for i in {1..30}; do
            STATUS=$(docker inspect --format '{{.State.Health.Status}}' nether-bridge || echo "inspecting")
            if [ "$STATUS" = "healthy" ]; then
              echo "Proxy is healthy!"
              exit 0
            fi
            echo "Current status: $STATUS. Waiting..."
            sleep 2
          done
          echo "Timeout waiting for proxy to become healthy."
          docker logs nether-bridge
          exit 1
      
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          # Install all dependencies needed for testing
          pip install -r tests/requirements-dev.txt

      - name: Run All Tests and Generate Coverage
        env:
          # This ensures the tests connect to the Docker host's localhost
          VM_HOST_IP: 127.0.0.1
        run: |
          pytest --cov=nether_bridge --cov-report term-missing tests/

      - name: Tear Down Test Environment
        if: always()
        run: |
          echo "Tearing down Docker Compose environment..."
          docker compose -f tests/docker-compose.tests.yml down -v --remove-orphans