name: Pull Request Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  validate-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # Install application and testing dependencies
          pip install -r requirements.txt
          pip install pytest pytest-mock pytest-cov

      - name: Run All Tests and Generate Coverage
        env:
          # Set the host IP for integration tests in the CI environment
          VM_HOST_IP: 127.0.0.1
        run: |
          # Run all unit and integration tests and generate a coverage report in the log
          pytest --cov=nether_bridge --cov-report term-missing tests/