name: Pull Request Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  validate-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create and build test environment
        run: |
          # Build all images and create the containers, but do not start them
          # This ensures mc-bedrock and mc-java exist in a 'created' state
          docker compose -f tests/docker-compose.tests.yml build

      - name: Start nether-bridge proxy
        run: |
          # Start only the nether-bridge service for the tests
          docker compose -f tests/docker-compose.tests.yml up -d nether-bridge

      - name: Wait for proxy to become healthy
        run: |
          echo "Waiting for nether-bridge to be healthy..."
          for i in {1..30}; do
            STATUS=$(docker inspect --format '{{.State.Health.Status}}' nether-bridge || echo "inspecting")
            if [ "$STATUS" = "healthy" ]; then
              echo "Proxy is healthy!"
              exit 0
            fi
            echo "Current status: $STATUS. Waiting..."
            sleep 2
          done
          echo "Timeout waiting for proxy to become healthy."
          docker logs nether-bridge
          exit 1
      
      - name: Run all tests
        run: |
          # Use 'docker compose run' to execute pytest inside the 'tester' container.
          # This command starts the tester service, runs pytest, and then removes the container.
          docker compose -f tests/docker-compose.tests.yml run --rm tester pytest --cov=nether_bridge --cov-report term-missing tests/
      
      - name: Tear down test environment
        if: always() # This step will run even if the tests fail
        run: |
          echo "Tearing down Docker Compose environment..."
          docker compose -f tests/docker-compose.tests.yml down -v --remove-orphans