# .github/workflows/pr-validation.yml
name: Pull Request Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  validate-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure local_env.py is absent in CI
        run: |
          rm -f tests/local_env.py || true

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # STEP 1: Install jq to ensure IP address lookup is reliable
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Force Rebuild Test Images (no cache)
        run: |
          docker compose -f tests/docker-compose.tests.yml build --no-cache nether-bridge nb-tester

      - name: Start Test Environment
        run: |
          docker compose -f tests/docker-compose.tests.yml up -d --remove-orphans
        id: start-env

      # STEP 2: Explicitly wait for the proxy to be healthy to avoid race conditions
      - name: Wait for Nether-bridge to be healthy
        run: |
          echo "Waiting for nether-bridge container to be healthy..."
          for i in {1..24}; do
            status=$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{end}}' nether-bridge)
            if [ "$status" == "healthy" ]; then
              echo "Nether-bridge is healthy!"
              exit 0
            fi
            echo "Current status: $status. Waiting 5s..."
            sleep 5
          done
          echo "Timeout: Nether-bridge did not become healthy after 2 minutes."
          exit 1

      - name: Run all tests
        run: |
          PROXY_IP=$(docker inspect nether-bridge | jq -r '.[0].NetworkSettings.Networks | .[] | .IPAddress')
          echo "Found nether-bridge IP: ${PROXY_IP}"
          docker compose -f tests/docker-compose.tests.yml exec -T nb-tester env CI_MODE=true PROXY_IP=${PROXY_IP} python -m pytest --cov=nether_bridge --cov-report term-missing
        id: run-tests

      - name: Dump All Container Logs on Failure
        if: ${{ failure() }}
        run: |
          echo "--- DUMPING ALL CONTAINER LOGS DUE TO FAILURE ---"
          docker compose -f tests/docker-compose.tests.yml ps -a
          echo "--- Docker Compose logs (all services) ---"
          docker compose -f tests/docker-compose.tests.yml logs --no-color
          echo "--- END LOG DUMP ---"

      - name: Tear down test environment
        if: always()
        run: |
          echo "Tearing down Docker Compose environment..."
          docker compose -f tests/docker-compose.tests.yml down -v --remove-orphans