name: Pull Request Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  validate-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Start Test Environment
        run: |
          # Use --project-directory . to ensure the context is the repository root
          docker compose --project-directory . -f tests/docker-compose.tests.yml up --build -d --remove-orphans nether-bridge

      - name: Show Directory Structure Inside Tester Container
        run: |
          echo "Listing files and directory structure inside the 'tester' container at /app..."
          # Also use --project-directory here for consistency
          docker compose --project-directory . -f tests/docker-compose.tests.yml run --rm tester ls -lR /app

      - name: Run all tests
        run: |
          # Use jq to parse the JSON output from docker inspect.
          PROXY_IP=$(docker inspect nether-bridge | jq -r '.[0].NetworkSettings.Networks | .[] | .IPAddress')
          echo "Found nether-bridge IP: ${PROXY_IP}"

          # Use --project-directory . and run pytest as a module.
          docker compose --project-directory . -f tests/docker-compose.tests.yml run -e VM_HOST_IP=$PROXY_IP --rm tester python -m pytest --cov=nether_bridge --cov-report term-missing
      
      - name: Tear down test environment
        if: always()
        run: |
          echo "Tearing down Docker Compose environment..."
          # Use --project-directory . for the final cleanup.
          docker compose --project-directory . -f tests/docker-compose.tests.yml down -v --remove-orphans