name: Pull Request Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  validate-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Start Test Environment
        run: |
          docker compose -f tests/docker-compose.tests.yml up --build -d --remove-orphans nether-bridge

      - name: Run all tests
        run: |
          # Step 1: Get the name of the docker-compose network.
          # We inspect the container and get the key of the first network it's attached to.
          NETWORK_NAME=$(docker inspect nether-bridge --format '{{range $k, $v := .NetworkSettings.Networks}}{{$k}}{{end}}')
          
          # Step 2: Use the network name to get the IP address for that network.
          # This is more robust and avoids template parsing errors with special characters.
          PROXY_IP=$(docker inspect -f "{{.NetworkSettings.Networks.${NETWORK_NAME}.IPAddress}}" nether-bridge)
          echo "Found nether-bridge IP on network '${NETWORK_NAME}': ${PROXY_IP}"

          # Step 3: Run pytest inside the tester container, passing the IP as an environment variable.
          docker compose -f tests/docker-compose.tests.yml run -e VM_HOST_IP=$PROXY_IP --rm tester pytest --cov=nether_bridge --cov-report term-missing tests/
      
      - name: Tear down test environment
        # This step runs even if tests fail, ensuring a clean exit.
        if: always()
        run: |
          echo "Tearing down Docker Compose environment..."
          docker compose -f tests/docker-compose.tests.yml down -v --remove-orphans