name: Pull Request Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  validate-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install All Dependencies
        run: |
          python -m pip install --upgrade pip
          # Install all app and dev dependencies from our new file
          pip install -r tests/requirements-dev.txt

      - name: Lint and Format Check
        run: |
          echo "Running linter (flake8)..."
          # Check for major errors first
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Check for general style issues
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          echo "Checking formatting (black)..."
          # The --check flag fails the build if code is not formatted
          black --check .

      - name: Run All Tests and Generate Coverage
        env:
          VM_HOST_IP: 127.0.0.1
        run: |
          # Run all tests (unit and integration) and generate a coverage report in the log
          pytest --cov=nether_bridge --cov-report term-missing tests/